Announce deprecation
globus/globus-timer-cli pull request #19
Opened 2023-08-16 22:16 UTC by kurtmckee

There are two README, and both are now stripped of content in favor of a simple deprecation announcement.

The project metadata has been updated as well to prepare for one last release to PyPI.

2023-08-16 22:31 UTC, tcooper commented
We use `globus-timer-cli` for important use case supporting ACCESS CI and we are also a paid Subscriber.

Unfortunate that this project is going from Beta directly to Inactive/Deprecated status but so it goes.

Would it be possible to add information beyond the, arguably inadequate, link to CLI docs? Perhaps an example implementation in workflows that can accomplish similar behaviors?

2023-08-17 20:29 UTC, kurtmckee commented
Hello @tcooper!

First, I want to affirm that the Timers service is not being deprecated.

I'm under the impression that it's the Timers service, not this specific CLI, that is supporting ACCESS CI, but I want to ensure that you're not losing critical functionality.

The functionality that this Timers CLI has offerred is now integrated into the Globus CLI, which includes a suite of comprehensive commands for interacting with Globus services including Timers, Flows, Search, Transfer, and Auth.

For example, given a Timer CLI command like the following:

```bash
globus-timer job transfer \
    --name example-job \
    --label 'Timer Transfer Job' \
    --interval 28800 \
    --start '2020-01-01T12:34:56' \
    --source-endpoint 45e0659e-3537-4fbd-a10f-947ff5142548 \
    --dest-endpoint ff8a3c3c-625a-4b28-a4f3-d4e8f3622952 \
    --item "/my/file.txt" "~/copy.txt" false
```

the equivalent command using the Globus CLI would be:

```bash
globus timer create transfer \
    --name example-job \
    --label 'Timer Transfer Job' \
    --interval 8h \
    --start '2020-01-01T12:34:56' \
    45e0659e-3537-4fbd-a10f-947ff5142548:/my/file.txt \
    ff8a3c3c-625a-4b28-a4f3-d4e8f3622952:~/copy.txt
```

Does this explanation clarify the situation? Are there other use cases or needs that could be addressed in an update to this PR? You can respond here, or email `support@globus.org` to open a ticket.

In either case, I've taken it as an action item to improve this PR so the deprecation text offers more information and support to users and customers.

2023-08-17 21:39 UTC, tcooper commented
@kurtmckee Thanks for providing this information and offering to update the PR.

Your example doesn't completely capture our use case. I will look at the globus CLI command for timer to see if all of the parameters we are using are possible.

A sample `globus-timer` CLI command we create (via a wrapper script) would look like the following...

```
$ GLOBUS_TIMER_CLI_JOB_START="2023-09-01T12:00:00-0700" \
GLOBUS_TIMER_CLI_JOB_STOP_AFTER_RUNS=30 ./setup_globus_timer_job.sh

You are about to scheduled the following globus-timer job...

globus-timer job transfer \
	--name expanse-slurm-accounting \
	--label 'EXPANSE Slurm Accounting Logs to ACCESS-CI XDMoD' \
	--interval 86400 \
	--stop-after-runs 30 \
	--sync-level 3 \
	--verify-checksum \
	--encrypt-data \
	--start 2023-09-01T12:00:00-0700 \
	--source-endpoint 8735b734-00dc-4659-be0d-ff96beaff17b \
	--dest-endpoint 4012c7a6-72c8-4674-a2e2-5ffe8ac7255c \
	--item /<some_parent_dir>/expanse/accounting_new /expanse/accounting True

Are you sure? y

Name:            expanse-slurm-accounting
Job ID:          9fd088a9-895e-4de2-9c15-0f8359f69c3c
Status:          new
Start:           2023-09-01T19:00:00+00:00
Interval:        1 day, 0:00:00
Next Run At:     2023-09-01T19:00:00+00:00
Last Run Result: NOT RUN
```

You can see from the above that we aren't scheduling a specific file to transfer. We're scheduling a directory sync between the two endpoints. For various reasons a directory sync is preferred over single file transfer resync.

Hopefully that sample helps you understand the use case we need to support using globus CLI.

2023-08-17 22:39 UTC, kurtmckee commented
@tcooper, I think your example can similarly be transformed, but it will highlight some differences in the CLI options' values.

The original Timer CLI command looks like this:

```bash
globus-timer job transfer \
	--name expanse-slurm-accounting \
	--label 'EXPANSE Slurm Accounting Logs to ACCESS-CI XDMoD' \
	--interval 86400 \
	--stop-after-runs 30 \
	--sync-level 3 \
	--verify-checksum \
	--encrypt-data \
	--start 2023-09-01T12:00:00-0700 \
	--source-endpoint 8735b734-00dc-4659-be0d-ff96beaff17b \
	--dest-endpoint 4012c7a6-72c8-4674-a2e2-5ffe8ac7255c \
	--item /<some_parent_dir>/expanse/accounting_new /expanse/accounting True
```

I think it will look like this when using the Globus CLI:

```bash
globus timer create transfer \
    --name expanse-slurm-accounting \
    --label 'EXPANSE Slurm Accounting Logs to ACCESS-CI XDMoD' \
    --interval 86400s \
    --stop-after-runs 30 \
    --sync-level checksum \
    --verify-checksum \
    --encrypt-data \
    --start 2023-09-01T12:00:00-0700 \
    --recursive \
    8735b734-00dc-4659-be0d-ff96beaff17b:/<some_parent_dir>/expanse/accounting_new \
    4012c7a6-72c8-4674-a2e2-5ffe8ac7255c:/expanse/accounting
```

The two commands are similar, but some of the values and flags have changed:

* `--interval` requires a unit, like `86400s`, `1440m`, `24h`, or even `1d`.

  These can be combined for clearer fine-grained control, like `8h30m`.

* `--sync-level` requires a word instead of a number.

  In this example the value is `checksum`, but `mtime`, `size`, and `exists` are also accepted.

* `--recursive` is required to flag a transfer as recursive, rather than a trailing `True`.

Are there other use cases that you're aware of? I'd like to take this as an opportunity to capture your feedback so you (and others!) are well-supported, and then create a migration guide that highlights these changes. I'll then update this PR to point to that guide.

Thanks for your time, and for sharing how you're using the Timers CLI!

2023-08-17 23:57 UTC, tcooper commented
That looks like all the options we are currently using are reimplemented in the github CLI.

Thanks for doing the work to remap all of our options for me!

I will test switching from the github-timer to github CLI to see if that uncovers other issues and report back.

2023-08-18 01:16 UTC, tcooper commented
Authentication steps are a little different but nothing that isn't easy to adjust for.

We have timer creation reimplemented using `globus timer create transfer ...` in place of `globus-timer job transfer...`.

Thanks for listening and your help.

2023-08-29 16:10 UTC, sirosen approved these changes, later dismissed
I see that we'll need to add `--no-recursive` to the batch processing in globus-cli for the migration guide to be fully accurate, but I'm giving this a pre-approval/contingent approval.

TBH, I would be fine with merging this with the minor inaccuracy that introduces and then working quickly to catch-up in globus-cli. Others may disagree on this though.

2023-08-29 16:35 UTC, kurtmckee commented
I have a branch for the Globus CLI to add this. I'm anticipating posting a PR for that today.

2023-08-29 17:25 UTC, ada-globus requested changes
This is great! I only have a couple very minor content notes. Most of the notes are re: GitHub's seemingly patchy support of RST features.

2023-08-29 17:25 UTC, ada-globus commented on MIGRATING.rst
> +    At the time of writing, there is no equivalent for this command in the Globus CLI.
Doesn't look like this renders as a note in GH. I think GH may not support admonitions in RST? If so, probably worth looking for an alternative way of presenting or switching to a format where they're supported (IIRC, this works in adoc, and GH has support for it in MD—see [new syntax introduced last month](https://github.com/orgs/community/discussions/16925#discussioncomment-6506860)).

2023-08-29 17:25 UTC, ada-globus commented on MIGRATING.rst
> +some of the options' values were modified.
```suggestion
some of the value formats have changed.
```

2023-08-29 17:25 UTC, ada-globus commented on MIGRATING.rst
> +        See the next bullet point for a discussion of the equivalent in the Globus CLI.
Doesn't render as a note (see above)

2023-08-29 17:25 UTC, ada-globus commented on MIGRATING.rst
> +        globus timer create transfer SRC_ID:SRC_PATH DST_ID:DST_PATH --no-recursive
This does not appear in the rendered page. I _think_ it might be related to the caption directive, but that's just a guess.

2023-08-29 17:25 UTC, ada-globus commented on MIGRATING.rst
> +
Worth adding an entry for ``--interval``? (location of this note is semi arbitrary)

2023-08-29 17:25 UTC, ada-globus commented on pypi/README.md
> +Please use the [Globus CLI](https://docs.globus.org/cli/) instead.
Let's also self-link to the migration guide

2023-08-29 17:27 UTC, ada-globus commented on MIGRATING.rst
> +        globus timer create transfer SRC_ID:SRC_PATH DST_ID:DST_PATH --no-recursive
Looks like this was fixed during my review! 👍

2023-08-29 17:30 UTC, ada-globus commented on pypi/README.md
> +Please use the [Globus CLI](https://docs.globus.org/cli/) instead.
Resolved while I was reviewing! 👍

2023-08-29 17:45 UTC, kurtmckee commented on MIGRATING.rst
> +    At the time of writing, there is no equivalent for this command in the Globus CLI.
Improved using this syntax:

```rst
..  pull-quote::

    **Note**

    My note goes here!
```

2023-08-29 18:50 UTC, ada-globus submitted a review, later dismissed

2023-08-29 19:17 UTC, kurtmckee commented on MIGRATING.rst
> +
Ah, yep, they have differences. This is now documented. Thanks!

2023-08-29 19:22 UTC, sirosen approved these changes

2023-08-29 19:51 UTC, ada-globus approved these changes

2023-09-01 15:26 UTC, merged